/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DemosCustomerIndexRouteImport } from './routes/demos/$customer/index'
import { Route as MarketingPartnersIndexRouteImport } from './routes/_marketing/partners/index'
import { Route as MarketingHelpIndexRouteImport } from './routes/_marketing/help/index'
import { Route as MarketingDemosIndexRouteImport } from './routes/_marketing/demos/index'
import { Route as MarketingCustomersIndexRouteImport } from './routes/_marketing/customers/index'
import { Route as MarketingContactIndexRouteImport } from './routes/_marketing/contact/index'
import { Route as MarketingCareersIndexRouteImport } from './routes/_marketing/careers/index'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing/blog/index'
import { Route as MarketingAboutIndexRouteImport } from './routes/_marketing/about/index'
import { Route as DemosCustomerSlugRouteImport } from './routes/demos/$customer/$slug'
import { Route as MarketingSolutionsHomeInstallationRouteImport } from './routes/_marketing/solutions/home-installation'
import { Route as MarketingSolutionsFleetMaintenanceRouteImport } from './routes/_marketing/solutions/fleet-maintenance'
import { Route as MarketingSolutionsClaimsIntegrityRouteImport } from './routes/_marketing/solutions/claims-integrity'
import { Route as MarketingPartnersSlugRouteImport } from './routes/_marketing/partners/$slug'
import { Route as MarketingLegalTermsRouteImport } from './routes/_marketing/legal/terms'
import { Route as MarketingLegalPrivacyPolicyRouteImport } from './routes/_marketing/legal/privacy-policy'
import { Route as MarketingCustomersSlugRouteImport } from './routes/_marketing/customers/$slug'
import { Route as MarketingContactSalesRouteImport } from './routes/_marketing/contact/sales'
import { Route as MarketingCareersSlugRouteImport } from './routes/_marketing/careers/$slug'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing/blog/$slug'
import { Route as MarketingHelpKnowledgeIndexRouteImport } from './routes/_marketing/help/knowledge/index'
import { Route as MarketingHelpKnowledgeTopicRouteImport } from './routes/_marketing/help/knowledge/$topic'
import { Route as MarketingHelpKnowledgeGuideSlugRouteImport } from './routes/_marketing/help/knowledge/guide/$slug'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DemosCustomerIndexRoute = DemosCustomerIndexRouteImport.update({
  id: '/demos/$customer/',
  path: '/demos/$customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPartnersIndexRoute = MarketingPartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpIndexRoute = MarketingHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemosIndexRoute = MarketingDemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCustomersIndexRoute = MarketingCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactIndexRoute = MarketingContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCareersIndexRoute = MarketingCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutIndexRoute = MarketingAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => MarketingRoute,
} as any)
const DemosCustomerSlugRoute = DemosCustomerSlugRouteImport.update({
  id: '/demos/$customer/$slug',
  path: '/demos/$customer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSolutionsHomeInstallationRoute =
  MarketingSolutionsHomeInstallationRouteImport.update({
    id: '/solutions/home-installation',
    path: '/solutions/home-installation',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingSolutionsFleetMaintenanceRoute =
  MarketingSolutionsFleetMaintenanceRouteImport.update({
    id: '/solutions/fleet-maintenance',
    path: '/solutions/fleet-maintenance',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingSolutionsClaimsIntegrityRoute =
  MarketingSolutionsClaimsIntegrityRouteImport.update({
    id: '/solutions/claims-integrity',
    path: '/solutions/claims-integrity',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingPartnersSlugRoute = MarketingPartnersSlugRouteImport.update({
  id: '/partners/$slug',
  path: '/partners/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalTermsRoute = MarketingLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLegalPrivacyPolicyRoute =
  MarketingLegalPrivacyPolicyRouteImport.update({
    id: '/legal/privacy-policy',
    path: '/legal/privacy-policy',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingCustomersSlugRoute = MarketingCustomersSlugRouteImport.update({
  id: '/customers/$slug',
  path: '/customers/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContactSalesRoute = MarketingContactSalesRouteImport.update({
  id: '/contact/sales',
  path: '/contact/sales',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCareersSlugRoute = MarketingCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpKnowledgeIndexRoute =
  MarketingHelpKnowledgeIndexRouteImport.update({
    id: '/help/knowledge/',
    path: '/help/knowledge/',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingHelpKnowledgeTopicRoute =
  MarketingHelpKnowledgeTopicRouteImport.update({
    id: '/help/knowledge/$topic',
    path: '/help/knowledge/$topic',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingHelpKnowledgeGuideSlugRoute =
  MarketingHelpKnowledgeGuideSlugRouteImport.update({
    id: '/help/knowledge/guide/$slug',
    path: '/help/knowledge/guide/$slug',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/careers/$slug': typeof MarketingCareersSlugRoute
  '/contact/sales': typeof MarketingContactSalesRoute
  '/customers/$slug': typeof MarketingCustomersSlugRoute
  '/legal/privacy-policy': typeof MarketingLegalPrivacyPolicyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/partners/$slug': typeof MarketingPartnersSlugRoute
  '/solutions/claims-integrity': typeof MarketingSolutionsClaimsIntegrityRoute
  '/solutions/fleet-maintenance': typeof MarketingSolutionsFleetMaintenanceRoute
  '/solutions/home-installation': typeof MarketingSolutionsHomeInstallationRoute
  '/demos/$customer/$slug': typeof DemosCustomerSlugRoute
  '/about/': typeof MarketingAboutIndexRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/careers/': typeof MarketingCareersIndexRoute
  '/contact/': typeof MarketingContactIndexRoute
  '/customers/': typeof MarketingCustomersIndexRoute
  '/demos/': typeof MarketingDemosIndexRoute
  '/help/': typeof MarketingHelpIndexRoute
  '/partners/': typeof MarketingPartnersIndexRoute
  '/demos/$customer/': typeof DemosCustomerIndexRoute
  '/help/knowledge/$topic': typeof MarketingHelpKnowledgeTopicRoute
  '/help/knowledge/': typeof MarketingHelpKnowledgeIndexRoute
  '/help/knowledge/guide/$slug': typeof MarketingHelpKnowledgeGuideSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/careers/$slug': typeof MarketingCareersSlugRoute
  '/contact/sales': typeof MarketingContactSalesRoute
  '/customers/$slug': typeof MarketingCustomersSlugRoute
  '/legal/privacy-policy': typeof MarketingLegalPrivacyPolicyRoute
  '/legal/terms': typeof MarketingLegalTermsRoute
  '/partners/$slug': typeof MarketingPartnersSlugRoute
  '/solutions/claims-integrity': typeof MarketingSolutionsClaimsIntegrityRoute
  '/solutions/fleet-maintenance': typeof MarketingSolutionsFleetMaintenanceRoute
  '/solutions/home-installation': typeof MarketingSolutionsHomeInstallationRoute
  '/demos/$customer/$slug': typeof DemosCustomerSlugRoute
  '/about': typeof MarketingAboutIndexRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/careers': typeof MarketingCareersIndexRoute
  '/contact': typeof MarketingContactIndexRoute
  '/customers': typeof MarketingCustomersIndexRoute
  '/demos': typeof MarketingDemosIndexRoute
  '/help': typeof MarketingHelpIndexRoute
  '/partners': typeof MarketingPartnersIndexRoute
  '/demos/$customer': typeof DemosCustomerIndexRoute
  '/help/knowledge/$topic': typeof MarketingHelpKnowledgeTopicRoute
  '/help/knowledge': typeof MarketingHelpKnowledgeIndexRoute
  '/help/knowledge/guide/$slug': typeof MarketingHelpKnowledgeGuideSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/careers/$slug': typeof MarketingCareersSlugRoute
  '/_marketing/contact/sales': typeof MarketingContactSalesRoute
  '/_marketing/customers/$slug': typeof MarketingCustomersSlugRoute
  '/_marketing/legal/privacy-policy': typeof MarketingLegalPrivacyPolicyRoute
  '/_marketing/legal/terms': typeof MarketingLegalTermsRoute
  '/_marketing/partners/$slug': typeof MarketingPartnersSlugRoute
  '/_marketing/solutions/claims-integrity': typeof MarketingSolutionsClaimsIntegrityRoute
  '/_marketing/solutions/fleet-maintenance': typeof MarketingSolutionsFleetMaintenanceRoute
  '/_marketing/solutions/home-installation': typeof MarketingSolutionsHomeInstallationRoute
  '/demos/$customer/$slug': typeof DemosCustomerSlugRoute
  '/_marketing/about/': typeof MarketingAboutIndexRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/_marketing/careers/': typeof MarketingCareersIndexRoute
  '/_marketing/contact/': typeof MarketingContactIndexRoute
  '/_marketing/customers/': typeof MarketingCustomersIndexRoute
  '/_marketing/demos/': typeof MarketingDemosIndexRoute
  '/_marketing/help/': typeof MarketingHelpIndexRoute
  '/_marketing/partners/': typeof MarketingPartnersIndexRoute
  '/demos/$customer/': typeof DemosCustomerIndexRoute
  '/_marketing/help/knowledge/$topic': typeof MarketingHelpKnowledgeTopicRoute
  '/_marketing/help/knowledge/': typeof MarketingHelpKnowledgeIndexRoute
  '/_marketing/help/knowledge/guide/$slug': typeof MarketingHelpKnowledgeGuideSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/contact/sales'
    | '/customers/$slug'
    | '/legal/privacy-policy'
    | '/legal/terms'
    | '/partners/$slug'
    | '/solutions/claims-integrity'
    | '/solutions/fleet-maintenance'
    | '/solutions/home-installation'
    | '/demos/$customer/$slug'
    | '/about/'
    | '/blog/'
    | '/careers/'
    | '/contact/'
    | '/customers/'
    | '/demos/'
    | '/help/'
    | '/partners/'
    | '/demos/$customer/'
    | '/help/knowledge/$topic'
    | '/help/knowledge/'
    | '/help/knowledge/guide/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/contact/sales'
    | '/customers/$slug'
    | '/legal/privacy-policy'
    | '/legal/terms'
    | '/partners/$slug'
    | '/solutions/claims-integrity'
    | '/solutions/fleet-maintenance'
    | '/solutions/home-installation'
    | '/demos/$customer/$slug'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/customers'
    | '/demos'
    | '/help'
    | '/partners'
    | '/demos/$customer'
    | '/help/knowledge/$topic'
    | '/help/knowledge'
    | '/help/knowledge/guide/$slug'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/'
    | '/_marketing/blog/$slug'
    | '/_marketing/careers/$slug'
    | '/_marketing/contact/sales'
    | '/_marketing/customers/$slug'
    | '/_marketing/legal/privacy-policy'
    | '/_marketing/legal/terms'
    | '/_marketing/partners/$slug'
    | '/_marketing/solutions/claims-integrity'
    | '/_marketing/solutions/fleet-maintenance'
    | '/_marketing/solutions/home-installation'
    | '/demos/$customer/$slug'
    | '/_marketing/about/'
    | '/_marketing/blog/'
    | '/_marketing/careers/'
    | '/_marketing/contact/'
    | '/_marketing/customers/'
    | '/_marketing/demos/'
    | '/_marketing/help/'
    | '/_marketing/partners/'
    | '/demos/$customer/'
    | '/_marketing/help/knowledge/$topic'
    | '/_marketing/help/knowledge/'
    | '/_marketing/help/knowledge/guide/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DemosCustomerSlugRoute: typeof DemosCustomerSlugRoute
  DemosCustomerIndexRoute: typeof DemosCustomerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/demos/$customer/': {
      id: '/demos/$customer/'
      path: '/demos/$customer'
      fullPath: '/demos/$customer/'
      preLoaderRoute: typeof DemosCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/partners/': {
      id: '/_marketing/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof MarketingPartnersIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help/': {
      id: '/_marketing/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof MarketingHelpIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demos/': {
      id: '/_marketing/demos/'
      path: '/demos'
      fullPath: '/demos/'
      preLoaderRoute: typeof MarketingDemosIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/customers/': {
      id: '/_marketing/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof MarketingCustomersIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact/': {
      id: '/_marketing/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof MarketingContactIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/careers/': {
      id: '/_marketing/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof MarketingCareersIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about/': {
      id: '/_marketing/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof MarketingAboutIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/demos/$customer/$slug': {
      id: '/demos/$customer/$slug'
      path: '/demos/$customer/$slug'
      fullPath: '/demos/$customer/$slug'
      preLoaderRoute: typeof DemosCustomerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/solutions/home-installation': {
      id: '/_marketing/solutions/home-installation'
      path: '/solutions/home-installation'
      fullPath: '/solutions/home-installation'
      preLoaderRoute: typeof MarketingSolutionsHomeInstallationRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/solutions/fleet-maintenance': {
      id: '/_marketing/solutions/fleet-maintenance'
      path: '/solutions/fleet-maintenance'
      fullPath: '/solutions/fleet-maintenance'
      preLoaderRoute: typeof MarketingSolutionsFleetMaintenanceRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/solutions/claims-integrity': {
      id: '/_marketing/solutions/claims-integrity'
      path: '/solutions/claims-integrity'
      fullPath: '/solutions/claims-integrity'
      preLoaderRoute: typeof MarketingSolutionsClaimsIntegrityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/partners/$slug': {
      id: '/_marketing/partners/$slug'
      path: '/partners/$slug'
      fullPath: '/partners/$slug'
      preLoaderRoute: typeof MarketingPartnersSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/terms': {
      id: '/_marketing/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof MarketingLegalTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/legal/privacy-policy': {
      id: '/_marketing/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof MarketingLegalPrivacyPolicyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/customers/$slug': {
      id: '/_marketing/customers/$slug'
      path: '/customers/$slug'
      fullPath: '/customers/$slug'
      preLoaderRoute: typeof MarketingCustomersSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contact/sales': {
      id: '/_marketing/contact/sales'
      path: '/contact/sales'
      fullPath: '/contact/sales'
      preLoaderRoute: typeof MarketingContactSalesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/careers/$slug': {
      id: '/_marketing/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof MarketingCareersSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help/knowledge/': {
      id: '/_marketing/help/knowledge/'
      path: '/help/knowledge'
      fullPath: '/help/knowledge/'
      preLoaderRoute: typeof MarketingHelpKnowledgeIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help/knowledge/$topic': {
      id: '/_marketing/help/knowledge/$topic'
      path: '/help/knowledge/$topic'
      fullPath: '/help/knowledge/$topic'
      preLoaderRoute: typeof MarketingHelpKnowledgeTopicRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help/knowledge/guide/$slug': {
      id: '/_marketing/help/knowledge/guide/$slug'
      path: '/help/knowledge/guide/$slug'
      fullPath: '/help/knowledge/guide/$slug'
      preLoaderRoute: typeof MarketingHelpKnowledgeGuideSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingCareersSlugRoute: typeof MarketingCareersSlugRoute
  MarketingContactSalesRoute: typeof MarketingContactSalesRoute
  MarketingCustomersSlugRoute: typeof MarketingCustomersSlugRoute
  MarketingLegalPrivacyPolicyRoute: typeof MarketingLegalPrivacyPolicyRoute
  MarketingLegalTermsRoute: typeof MarketingLegalTermsRoute
  MarketingPartnersSlugRoute: typeof MarketingPartnersSlugRoute
  MarketingSolutionsClaimsIntegrityRoute: typeof MarketingSolutionsClaimsIntegrityRoute
  MarketingSolutionsFleetMaintenanceRoute: typeof MarketingSolutionsFleetMaintenanceRoute
  MarketingSolutionsHomeInstallationRoute: typeof MarketingSolutionsHomeInstallationRoute
  MarketingAboutIndexRoute: typeof MarketingAboutIndexRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
  MarketingCareersIndexRoute: typeof MarketingCareersIndexRoute
  MarketingContactIndexRoute: typeof MarketingContactIndexRoute
  MarketingCustomersIndexRoute: typeof MarketingCustomersIndexRoute
  MarketingDemosIndexRoute: typeof MarketingDemosIndexRoute
  MarketingHelpIndexRoute: typeof MarketingHelpIndexRoute
  MarketingPartnersIndexRoute: typeof MarketingPartnersIndexRoute
  MarketingHelpKnowledgeTopicRoute: typeof MarketingHelpKnowledgeTopicRoute
  MarketingHelpKnowledgeIndexRoute: typeof MarketingHelpKnowledgeIndexRoute
  MarketingHelpKnowledgeGuideSlugRoute: typeof MarketingHelpKnowledgeGuideSlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingCareersSlugRoute: MarketingCareersSlugRoute,
  MarketingContactSalesRoute: MarketingContactSalesRoute,
  MarketingCustomersSlugRoute: MarketingCustomersSlugRoute,
  MarketingLegalPrivacyPolicyRoute: MarketingLegalPrivacyPolicyRoute,
  MarketingLegalTermsRoute: MarketingLegalTermsRoute,
  MarketingPartnersSlugRoute: MarketingPartnersSlugRoute,
  MarketingSolutionsClaimsIntegrityRoute:
    MarketingSolutionsClaimsIntegrityRoute,
  MarketingSolutionsFleetMaintenanceRoute:
    MarketingSolutionsFleetMaintenanceRoute,
  MarketingSolutionsHomeInstallationRoute:
    MarketingSolutionsHomeInstallationRoute,
  MarketingAboutIndexRoute: MarketingAboutIndexRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
  MarketingCareersIndexRoute: MarketingCareersIndexRoute,
  MarketingContactIndexRoute: MarketingContactIndexRoute,
  MarketingCustomersIndexRoute: MarketingCustomersIndexRoute,
  MarketingDemosIndexRoute: MarketingDemosIndexRoute,
  MarketingHelpIndexRoute: MarketingHelpIndexRoute,
  MarketingPartnersIndexRoute: MarketingPartnersIndexRoute,
  MarketingHelpKnowledgeTopicRoute: MarketingHelpKnowledgeTopicRoute,
  MarketingHelpKnowledgeIndexRoute: MarketingHelpKnowledgeIndexRoute,
  MarketingHelpKnowledgeGuideSlugRoute: MarketingHelpKnowledgeGuideSlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DemosCustomerSlugRoute: DemosCustomerSlugRoute,
  DemosCustomerIndexRoute: DemosCustomerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
